# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(886, 781)
        self.EbayTab = QtWidgets.QTabWidget(Form)
        self.EbayTab.setGeometry(QtCore.QRect(10, 130, 851, 261))
        self.EbayTab.setObjectName("EbayTab")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.shopifyOrdersUploadButton = QtWidgets.QPushButton(self.tab)
        self.shopifyOrdersUploadButton.setGeometry(QtCore.QRect(360, 30, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.shopifyOrdersUploadButton.setFont(font)
        self.shopifyOrdersUploadButton.setCheckable(False)
        self.shopifyOrdersUploadButton.setObjectName("shopifyOrdersUploadButton")
        self.GenerateUPSLabelsforShopify = QtWidgets.QPushButton(self.tab)
        self.GenerateUPSLabelsforShopify.setGeometry(QtCore.QRect(260, 100, 281, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.GenerateUPSLabelsforShopify.setFont(font)
        self.GenerateUPSLabelsforShopify.setObjectName("GenerateUPSLabelsforShopify")
        self.GenerateParcelForceLabelsforShopify = QtWidgets.QPushButton(self.tab)
        self.GenerateParcelForceLabelsforShopify.setGeometry(QtCore.QRect(540, 100, 281, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.GenerateParcelForceLabelsforShopify.setFont(font)
        self.GenerateParcelForceLabelsforShopify.setObjectName("GenerateParcelForceLabelsforShopify")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(90, 40, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.UPSTrackingUploadforShopify = QtWidgets.QPushButton(self.tab)
        self.UPSTrackingUploadforShopify.setGeometry(QtCore.QRect(520, 30, 301, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.UPSTrackingUploadforShopify.setFont(font)
        self.UPSTrackingUploadforShopify.setCheckable(False)
        self.UPSTrackingUploadforShopify.setObjectName("UPSTrackingUploadforShopify")
        self.DownloadShopify = QtWidgets.QPushButton(self.tab)
        self.DownloadShopify.setGeometry(QtCore.QRect(540, 160, 281, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.DownloadShopify.setFont(font)
        self.DownloadShopify.setObjectName("DownloadShopify")
        self.EbayTab.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.ebayOrderUpload = QtWidgets.QPushButton(self.tab_2)
        self.ebayOrderUpload.setGeometry(QtCore.QRect(420, 20, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.ebayOrderUpload.setFont(font)
        self.ebayOrderUpload.setCheckable(False)
        self.ebayOrderUpload.setObjectName("ebayOrderUpload")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(150, 40, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.GenerateUPSforEbay = QtWidgets.QPushButton(self.tab_2)
        self.GenerateUPSforEbay.setGeometry(QtCore.QRect(530, 80, 281, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.GenerateUPSforEbay.setFont(font)
        self.GenerateUPSforEbay.setObjectName("GenerateUPSforEbay")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_6.setGeometry(QtCore.QRect(120, 80, 411, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setCheckable(False)
        self.pushButton_6.setChecked(False)
        self.pushButton_6.setObjectName("pushButton_6")
        self.UPSTrackingUpload = QtWidgets.QPushButton(self.tab_2)
        self.UPSTrackingUpload.setGeometry(QtCore.QRect(590, 20, 221, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.UPSTrackingUpload.setFont(font)
        self.UPSTrackingUpload.setCheckable(False)
        self.UPSTrackingUpload.setObjectName("UPSTrackingUpload")
        self.DownloadEbay = QtWidgets.QPushButton(self.tab_2)
        self.DownloadEbay.setGeometry(QtCore.QRect(530, 140, 281, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.DownloadEbay.setFont(font)
        self.DownloadEbay.setObjectName("DownloadEbay")
        self.EbayTab.addTab(self.tab_2, "")
        self.SuccessCount = QtWidgets.QLCDNumber(Form)
        self.SuccessCount.setGeometry(QtCore.QRect(650, 20, 191, 71))
        self.SuccessCount.setObjectName("SuccessCount")
        self.resultPanel = QtWidgets.QTextBrowser(Form)
        self.resultPanel.setGeometry(QtCore.QRect(10, 410, 851, 321))
        self.resultPanel.setObjectName("resultPanel")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(450, 45, 181, 31))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Form)
        self.EbayTab.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.shopifyOrdersUploadButton.setText(_translate("Form", "Upload"))
        self.GenerateUPSLabelsforShopify.setText(_translate("Form", "Generate UPS labels"))
        self.GenerateParcelForceLabelsforShopify.setText(_translate("Form", "Generate Parcel force labels"))
        self.label.setText(_translate("Form", "Upload the orders from shopify here"))
        self.UPSTrackingUploadforShopify.setText(_translate("Form", "Upload Tracking Number for UPS"))
        self.DownloadShopify.setText(_translate("Form", "Download"))
        self.EbayTab.setTabText(self.EbayTab.indexOf(self.tab), _translate("Form", "Shopify"))
        self.ebayOrderUpload.setText(_translate("Form", "Order Upload"))
        self.label_3.setText(_translate("Form", "Upload the orders from shopify here"))
        self.GenerateUPSforEbay.setText(_translate("Form", "Generate UPS labels"))
        self.pushButton_6.setText(_translate("Form", "Prepare Tracking Numbers from UPS file"))
        self.UPSTrackingUpload.setText(_translate("Form", "UPS Tracking Upload"))
        self.DownloadEbay.setText(_translate("Form", "Download"))
        self.EbayTab.setTabText(self.EbayTab.indexOf(self.tab_2), _translate("Form", "Ebay"))
        self.label_2.setText(_translate("Form", "Number of successful orders"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
